base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

planner_frequency: 0.2
shutdown_costmaps: true
controller_frequency: 3.0
recovery_behaviour_enabled: false
clearing_rotation_allowed: false
